# -*- coding: utf-8 -*-
"""
01_ElementosPython_Quispe.ipynb

Automatically generated by Colaboratory.

**EJERCITACIÓN INICIAL**

> Función print()

    Esta función muestra en pantalla lo que escribamos como argumento.
"""

print("Hola! Esta es mi primera línea de código.")

print("Me llamo Santiago.")
print("Mis compañeros de grupo son:")
print("Belen\nHéctor\nMarisa\nVero")

"""
> Variables

Una variable es un contenedor donde almacenaremos valores.
"""

alumno = "Santiago"
edad = 20
print(alumno, edad)

num1 = 100
num2 = 150

suma = num1 + num2

print("La suma de ambos valores es: ", suma)

numero1 = 500
numero2 = 300

suma = numero1 + numero2
resta = numero1 - numero2
multi = numero1 * numero2

print("La suma es: ", suma)
print("La resta es: ", resta)
print("La multiplicación es: ", multi)

# Ejercicio para calcular el área de un triángulo
base = 9.75
altura = 7.4

area = (base*altura)/2

print("El área del triángulo es: ", round(area,2))

"""
Muy bien realizados los ejercicios Santiago.

Nota = 10
"""