# -*- coding: utf-8 -*-
"""
02_ElementosPython_Quispe.ipynb

Automatically generated by Colaboratory.

> Entrada de datos mediante INPUT

La función input() lee una línea desde teclado, la convierte a cadena de texto (string) y la devuelve como resultado.
"""

nombre = input("¿Cuál es tu nombre? ")

print("Hola", nombre,"!")

# Ejercicio para culcular el área de un triángulo

base = float(input("Ingrese la base del triángulo: "))
altura = float(input("Ingrese la altura del triángulo: "))

area = (base * altura)/2

print("El área del triángulo es: ", area)

# Ejercicio para el cálculo de suma y promedio
num1 = int(input("Introduce un primer número entero: "))
num2 = int(input("Introduce un segundo número entero: "))
num3 = int(input("Introduce un tercer número entero: "))

suma = num1 + num2 + num3
promedio = suma / 3

print("La sumatoria de los números es: ", suma, "\5nY el promedio es: ", promedio)

# Ejercicio para calcular i.m.c
peso = float(input("Introduce su peso (en kilogramos): "))
altura = float(input("Introduce su altura (en metros): "))

imc = peso/(altura**2)

print("Tu índice de masa corporal es: ", round(imc,21))

# Ejercicio para calcular peso de paquetes
cant_reloj = int(input("Introduce cantidad de Relojes Digitales: "))
cant_auriculares = int(input("Introduce cantidad de Auriculares Inalámbricos:"))

peso_reloj = 25
peso_auriculares = 10

peso_total = (cant_reloj * peso_reloj) + (cant_auriculares * peso_auriculares)

print("El peso total de los paquetes es: ", peso_total)

"""
En un negocio de fotocopias, el dueño llamado Santiago Quispe decide crear un programa en Python para calcular el precio de los pedidos de sus clientes con lo aprendido de la diplomatura de Ledesma y FI-UNJu.

Para ello, toma de datos:
- Los precios de fotocopia particular: 10 Pesos c/u
- Los precios de fotocopia color: 20 Pesos c/u

Los datos que debe introducir en el programa son:

1.   Cantidad de fotocopias particulares
2.   Cantidad de fotocopias color

Con ellos se multiplican la cantidad de fotocopia por el precio determinado en cada tipo que sumados darían como resultado el Precio Final del pedido de sus clientes.
"""

# Problema Personal: Calcular precio total de los productos del cliente
precio_copia_particular = 10
precio_copia_color = 20

cant_copia_particular = int(input("Introduce la cantidad de copias particulares: "))
cant_copia_color = int(input("Introduce la cantidad de copias a color: "))

precio_total_particular = cant_copia_particular * precio_copia_particular
precio_total_color = cant_copia_color * precio_copia_color
precio_final = precio_total_particular + precio_total_color

print("El precio total de fotocopias particulares es:", precio_total_particular)
print("El precio total de fotocopias a colores es:", precio_total_color)
print("El precio total del pedido es: ", precio_final)

"""
Excelente tu caso práctico Santiago!!

Lo único que deberías revisar es la línea 5 del ejercicio de cálculo i.m.c.,  el nombre de la variable,  el cálculo, es diferente a la que se le asigna la estatura. 


Lo demás todo bien.

Nota = 9,75
"""