# -*- coding: utf-8 -*-
"""
ejercicio_grupal_quispe.ipynb

Automatically generated by Colaboratory.

EJERCICIO GRUPAL: Crear una función llamada "eliminar(lista, indice)" que reciba una lista y un número entero.

Esta debe verificar si el número está entre 0 y la última posición de la lista si es así, eliminar la posición de dicho índice y devolver la lista nueva, sino devolver la lista sin modificar.

Crear una lista de productos con 5 elementos.
Solicitar por pantalla el índice a eliminar.
"""

def eliminar(lista, indice):
  if indice >= 0 and indice <= len(lista):
    lista.pop(indice)
    print("Elemento eliminado")
  else:
    print("Indice fuera de rango")
    
  return lista

productos = ["cafe", "te", "fideos", "galletas", "azucar"]

indice = int(input("Ingrese el número de indice: "))

eliminar(productos, indice)