# -*- coding: utf-8 -*-
"""
EjercitaciónFinal_Quispe.ipynb

Automatically generated by Colaboratory.
"""

# Mi Diccionario de Datos Personales
datos_personales = {"nombre":"NAMESPACE", "dni":12345678, "edad":20, "sexo":"Masculino", "estudios":"Secundario Completo", "nacionalidad":"Argentina"}

# Llamar datos actuales
print(datos_personales)

# Booleano Borrar Datos
eliminar_datos = True

# Lista Vacía de Eliminados
lista_eliminados = []

# Bucle de Borrado
while eliminar_datos == True:
  # Ingresar dato a eliminar
  dato_eliminado = input("Ingrese una clave a eliminar (En MAYÚSCULA y FIN para terminar)")

  # Condicionales
  if dato_eliminado == "nombre":
    datos_personales.pop("nombre")
    lista_eliminados.append("Nombre")
    print("CLAVE NOMBRE ELIMINADA")
  elif dato_eliminado == "dni":
    datos_personales.pop("dni")
    lista_eliminados.append("DNI")
    print("CLAVE DNI ELIMINADA")
  elif dato_eliminado == "edad":
    datos_personales.pop("edad")
    lista_eliminados.append("Edad")
    print("CLAVE EDAD ELIMINADA")
  elif dato_eliminado == "sexo":
    datos_personales.pop("sexo")
    lista_eliminados.append("Sexo")
    print("CLAVE SEXO ELIMINADA")
  elif dato_eliminado == "estudios":
    datos_personales.pop("estudios")
    lista_eliminados.append("Estudios")
    print("CLAVE ESTUDIOS ELIMINADA")
  elif dato_eliminado == "nacionalidad":
    datos_personales.pop("nacionalidad")
    lista_eliminados.append("Nacionalidad")
    print("CLAVE NACIONALIDAD ELIMINADA")
  elif dato_eliminado == "fin":
    print("Proceso terminado...")
    break
  else:
    print("DATO INCORRECTO")
  
print("El diccionario resultando es: " + str(datos_personales))
print("Las claves eliminadas son: " + str(lista_eliminados))