# -*- coding: utf-8 -*-
"""
EstructurasControl_Grupo9.ipynb

Automatically generated by Colaboratory.
"""

# Programa 1: Muestra por pantalla el mensaje "Buenos días!!", cuando el nombre ingresado sea igual a "Juan".
 
nombre = input("Ingresar nombre: ")

if nombre == "Juan":
  print("Buenos dias!!")
else:
  print("Ingrese otro nombre")

# Programa 2: Preguntar si calcular el área de un triángulo o la de un círculo.
calcular = input("¿Deseas calcular el área de un triángulo (T) o la de un círculo (C)?")

if calcular == "T" or calcular == "t":
  base = int(input("Introduzca la base: "))
  altura = int(input("Introduzca la altura: "))

  area_triangulo = base * altura / 2
  print("El área del triángulo es: ", round(area_triangulo, 2))
elif calcular == "C" or calcular == "c":
  radio = float(input("Introduce el radio del círculo: "))

  area_circulo = 3.141592 * radio ** 2
  print("El área del círculo es: ", round(area_circulo, 2))
else:
  print("No reconozco esa letra. Adiós!")

# Programa 3: Solicitar un número entero, mostrar los 5 números consecutivos al ingresado.

num = input("Introduce un número entero:")

for i in range (0, 7):
  print(i)

# Programa 4: Solicitar número de vueltas. Luego iterar el mensaje "Vuelta" seguida del número correspondiente. Inclusive, iterar entre 1 y el número ingresado por el usuario.
vuelta = int(input("Ingrese número de vueltas: "))

for i in range(1, vuelta):
  vuelta -=1
  print("Vuelta: ", vuelta)

# Programa 5: Solicitar dos números enteros (un mínimo y un máximo). Luego solicitar números enteros situados entre ellos.
cant_num = 0
num_min = int(input("Introduce un número entero mínimo: "))
num_max = int(input("Introduce un número entero máximo: "))

num_input = int(input("Introduce tu número entero: "))

while num_input > num_min and num_input < num_max:
  cant_num += 1
  print("Número ingresado.")
  num_input = int(input("Introduce otro número entero: "))

print("Escribió un número fuera de rango.\nLa cantidad de números ingresados fueron: ", cant_num)